name: Test
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    types:
      - checks_requested
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - run: yarn install
      - run: |
          set -o pipefail
          mkdir -p ./pr
          echo ${{ github.event.number }} | tee ./pr/number
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "all_result<<$EOF" >> "$GITHUB_ENV"
          yarn all >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"
        id: all
      - uses: ./
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          header: All
          message: |
            <details open>
            <summary>output of yarn all</summary>

            ```
            ${{ env.all_result }}
            ```
            </details>
      - uses: ./
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          header: All
          append: true
          hide_details: true
          message: |
            The build is over.
